<?php

/**
 * @file
 * Contains wikipedia_search.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_FORM_ID_alter().
 */
function wikipedia_search_form_wikipedia_search_form_alter(&$form, FormStateInterface $form_state) {
  $form['form_build_id']['#access'] = FALSE;
  $form['form_token']['#access'] = FALSE;
  $form['form_id']['#access'] = FALSE;
}

/**
 * Implements hook_theme().
 */
function wikipedia_search_theme($existing, $type, $theme, $path) {
  return [
    'search_results' => [
      'variables' => ['data' => NULL],
      'template' => 'search_results',
    ],
    'article' => [
      'variables' => ['data' => NULL],
      'template' => 'article',
    ],
    'about' => [
      'template' => 'about',
    ],
  ];
}
